### PR TITLE
TypeScript definitions generation fix, peer dependencies fix

### LINKED ISSUE #16: Update peer dependencies to use 16.8 >
Please update peer dependencies to use the release version.

### LINKED ISSUE #17: Generate type definitions for TypeScript
Generate type definitions for TypeScript and not only JS bundle. You can use `tsc` for that with option `emitDeclarationOnly` and don't forget to add `typings` url to the `package.json`.

### PR DESCRIPTION
**Pull request by RIP21**
Closes #16, Fixes #17
- Unneeded react-hooks.d.ts removed
- Bump of the typings for libraries
- Fixes of some code to match the typings
- AllowJs to false to be able to generate typings
- Added typings for react-kawaii and react-sparklines for better example typing.

### CODE REVIEW

File: src/lib/inspector/index.tsx [hunk 1]
```diff
@@ -30,15 +30,14 @@ export interface Props {
   theme?: Theme;
 }
 
-export const Inspector: SFC<Props> = ({
```
Comment (RIP21) [inline src/lib/inspector/index.tsx]: SFC are deprecated in favor of FC

File: tsconfig.json [hunk 2]
```diff
@@ -19,7 +18,9 @@
     "experimentalDecorators": true,
     "skipLibCheck": true,
     "declaration": true,
-    "declarationDir": "/lib"
+    "emitDeclarationOnly": true
   },
-  "exclude": []
+  "exclude": [
```
Comment (RIP21) [inline tsconfig.json]: This one is added so typings from example files are not generated. In the next PRs, it may be beneficial to extract example out of the src to be able to typecheck it too by a separate tsconfig.json but it's rather not really important.

File: src/lib/knobs/useObject/object.tsx [hunk 3]
```diff
@@ -15,7 +15,7 @@ const Container = styled.div`
 
 interface Props {
   name: string;
-  value: number;
+  value: object;
```
Comment (RIP21) [inline src/lib/knobs/useObject/object.tsx]: This change caused by ReactJson typings. They state that it should be an object.

**Comment by Raathigesh** [comment]
This is awesome. Thank you 👍

**Comment by RIP21** [comment]
You're welcome :)

czw., 28 lut 2019, 11:42 użytkownik Raathi Kugarajan <
notifications@github.com> napisał:
